"""added interval_seconds field

Revision ID: 4eb68411b0fd
Revises: 92487ec36ec5
Create Date: 2026-02-14 19:03:10.689037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb68411b0fd'
down_revision: Union[str, Sequence[str], None] = '92487ec36ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_servers', sa.Column('interval_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_servers', 'interval_seconds')
    # ### end Alembic commands ###
